import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    marginTop: 30,
    padding: 20,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '105%',
    marginBottom: 30,
  },
  input: {
    backgroundColor: 'transparent',
    borderRadius: 8,
    borderBottomWidth: 0,
  },
  startButton: {
    width: '100%',
    height: 300,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    marginBottom: 80,
  },
  outerCircle: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 260,
    height: 260,
    borderRadius: 180,
    borderWidth: 7.5,
    borderColor: '#2BB3E0',
  },
  middleCircle: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 230,
    height: 230,
    borderRadius: 180,
    borderWidth: 7.5,
    borderColor: '#6E21D150',
  },
  innerCircle: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 190,
    height: 190,
    borderRadius: 180,
    borderWidth: 7.5,
    borderColor: '#2BB3E0',
  },
  buttonContainerStyle: {
    width: 150,
    height: 150,
    backgroundColor: '#6E21D150',
    borderRadius: 180,
  },
  buttonTitleStyle: {
    fontWeight: '700',
    fontSize: 30,
    color: '#FEFEFE',
  },
  timerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    height: 100,
    padding: 20,
    backgroundColor: '#FFFFFF20',
    borderRadius: 8,
  },
  timerInputContainer: {
    borderRadius: 8,
    borderBottomWidth: 0,
  },
  timerContainerStyle: {
    width: '40%',
    height: '100%',
    paddingTop: 8,
  },
});
